
spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true
    username: root
    password: sw1185
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
    static-path-pattern: /resources/**
    
  jpa:
    show-sql: true #JAP 수행 시 SQL문 로그 출력